spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/userboot
    schemas: public
    user: postgres
    password: postgres
    locations: classpath:db

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true
---
spring:
  kafka:
    template:
      default-topic: notification
    bootstrap-servers:
      - localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8901/oauth/check_token

server:
  port: 8082

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG