spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/userboot
    user: postgres
    password: postgres

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true
---
spring:
  kafka:
    template:
      default-topic: notification
    bootstrap-servers:
      - localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082