server:
  port: 8901

spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/securityboot
    user: postgres
    password: postgres

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securityboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true

---
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

---
#define Redis setup
spring:
  redis:
    host: localhost
    port: 6379

---
security-boot:
  jwt:
    secret: w1nd4nurm4l4