server:
  port: 8901

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

---
#define Redis setup
spring:
  redis:
    host: localhost
    port: 6379

---
security-boot:
  jwt:
    secret: w1nd4nurm4l4