spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/notificationboot
    user: postgres
    password: postgres

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

---
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true
---
spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: notification-group-id
server:
  port: 8081